document.addEventListener("DOMContentLoaded", function(event) { document.createElement('form').submit.call(document.getElementById('yourform')); }); 
function xjudisuhu() {location.replace("https://masuktanpavpnselamanya.on.drv.tw/links/judisuhu/");}
function xfreebet() {window.open("./link/freebet/index.html");}
function xpphoki() {window.open("./link/pphoki/index.html");}
function xlotto01() {window.open("./link/lotto01/index.html");}
function x8togel() {window.open("./link/8togel/index.html");}
function xbom29toto() {window.open("./link/bom29toto/index.html");}
function xlembagatoto() {window.open("./link/lembagatoto/index.html");}
function xhoki177() {window.open("./link/hoki177/index.html");}
function xtokekwin() {window.open("./link/tokekwin/index.html");}
function xbetcoinasia() {window.open("./link/betcoinasia/index.html");}
function xlotuspelangi() {window.open("./link/lotuspelangi/index.html");}
function xkijangwin() {window.open("./link/kijangwin/index.html");}
function xmpo222() {window.open("./link/mpo222/index.html");}
function xskslot() {window.open("./link/skslot/index.html");}
function xplaza4d() {window.open("./link/plaza4d/index.html");}
function xratu89() {window.open("./link/ratu89/index.html");}
function xagenslot168() {window.open("./link/agenslot168/index.html");}
function xaquaslot() {window.open("./link/aquaslot/index.html");}
function xdewakoin() {window.open("./link/dewakoin/index.html");}
function xgacorslot() {window.open("./link/gacorslot/index.html");}
function x303hoki() {window.open("./link/303hoki/index.html");}
function xjet88bet() {window.open("./link/jet88bet/index.html");}
function xmpo369() {window.open("./link/mpo369/index.html");}
function xeqn777() {window.open("./link/eqn777/index.html");}
function xunoplay() {window.open("./link/unoplay/index.html");}
function xkenzo188() {window.open("./link/kenzo188/index.html");}
function xnewliga365() {window.open("./link/newliga365/index.html");}
function xroyal123() {window.open("./link/royal123/index.html");}
function xsquad777() {window.open("./link/squad777/index.html");}
function x8bettingan() {window.open("./link/8bettingan/index.html");}
function xdewa234() {window.open("./link/dewa234/index.html");}
function xsweet777() {window.open("./link/sweet777/index.html");}
function xpoa88() {window.open("./link/poa88/index.html");}
function xharbet35() {window.open("./link/harbet35/index.html");}
function xslotoppo88() {window.open("./link/slotoppo88/index.html");}
function xpusaka787() {window.open("./link/pusaka787/index.html");}
function xcoblos4d() {window.open("./link/coblos4d/index.html");}
function xwisdom77() {window.open("./link/wisdom77/index.html");}
function xdiva168() {window.open("./link/diva168/index.html");}
function xjudi388() {window.open("./link/judi388/index.html");}
function xmpo666() {window.open("./link/mpo666/index.html");}
function xmpo555() {window.open("./link/mpo555/index.html");}
function xcvtogel() {window.open("./link/cvtogel/index.html");}
function xmpo08() {window.open("./link/mpo08/index.html");}
function xkadobet() {window.open("./link/kadobet/index.html");}
function xkas138() {window.open("./link/kas138/index.html");}
function xmega55() {window.open("./link/mega55/index.html");}
function xwishslot() {window.open("./link/wishslot/index.html");}
function xxuxu4d() {window.open("./link/xuxu4d/index.html");}
function xspesial303() {window.open("./link/spesial303/index.html");}
function xpintutogel() {window.open("./link/pintutogel/index.html");}
function xnyaitogel() {window.open("./link/nyaitogel/index.html");}
function xaurajp() {window.open("./link/aurajp/index.html");}
function xdauntogel() {window.open("./link/dauntogel/index.html");}
function xpiontogel() {window.open("./link/piontogel/index.html");}
function xalexabet88() {window.open("./link/alexabet88/index.html");}
function xole777() {window.open("./link/ole777/index.html");}
function xjadijp() {window.open("./link/jadijp/index.html");}
function xkoin313() {window.open("./link/koin313/index.html");}
function xarobet88() {window.open("./link/arobet88/index.html");}
function xaw8() {window.open("./link/aw8/index.html");}
function xrusia777() {window.open("./link/rusia777/index.html");}
function xkaikoslot() {window.open("./link/kaikoslot/index.html");}
function xserbacasino() {window.open("./link/serbacasino/index.html");}
function xhoki77() {window.open("./link/hoki77/index.html");}
function xpepe77() {window.open("./link/pepe77/index.html");}
function xolympus188() {window.open("./link/olympus188/index.html");}
